#!/bin/bash
rm ../res/drawable-hdpi/app_icon.$2 2>/dev/null
#rm ../res/drawable-mdpi/app_icon.$2 2>/dev/null
#rm ../res/drawable-ldpi/app_icon.$2 2>/dev/null
convert ../images/$1.$2 -resize 144x72 ../res/drawable-hdpi/app_icon.$2
#convert ../images/$1.$2 -resize 96x48  ../res/drawable-mdpi/app_icon.$2
#convert ../images/$1.$2 -resize 72x36  ../res/drawable-ldpi/app_icon.$2
